version: '3'
services:
    app-nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        depends_on:
            - app-fpm
    app-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./:/var/www
    app-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
            - ./:/var/www
        working_dir: /var/www
        tty: true
